- name: Deploy WebRTC signalling server to Docker
  community.docker.docker_compose:
    project_name: signal
    definition:
      version: '2'
      services:
        web:
          image: ghcr.io/czm1k3/webrtc-signalling-server:9c5456e
          ports:
            - "8001:3000"
          restart: always
