- name: Deploy MHD to Docker
  community.docker.docker_compose:
    project_name: mhd
    definition:
      version: '2'
      services:
        web:
          image: ghcr.io/czm1k3/pardubicemhd:sha-037bfcb
          environment:
            - FETCH_URL=http://fetcher:3000
          ports:
            - "8000:3000"
          depends_on:
            - fetcher
          restart: always
        fetcher:
          image: registry.gitlab.com/czm1k3/mhd-fefetch:latest
          restart: always
